# Generated by Django 5.1.6 on 2025-03-07 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='my_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_course', to='course.maincourse'),
        ),
    ]
