# Generated by Django 5.1.6 on 2025-03-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_users_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='users_course',
            new_name='my_course',
        ),
    ]
