# Generated by Django 5.1.6 on 2025-03-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('users', '0003_alter_student_options_student_purchased_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='purchased_courses',
        ),
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='course.maincourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_courses', to='users.student')),
            ],
        ),
    ]
