# Generated by Django 5.1.6 on 2025-03-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_favorite_user'),
        ('users', '0003_rename_users_course_student_my_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_course', to='course.maincourse'),
            preserve_default=False,
        ),
    ]
