# Generated by Django 5.1.6 on 2025-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_groupmember_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status_course',
            field=models.CharField(choices=[('free', 'free'), ('paid', 'paid'), ('mine', 'mine')], default='free', max_length=111),
        ),
    ]
