# Generated by Django 5.1.6 on 2025-03-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_status_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status_course',
        ),
    ]
