# Generated by Django 5.1.6 on 2025-03-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to='users.student'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_item', to='course.favorite'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_lessons', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_favorite', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_course', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='course.lesson'),
        ),
        migrations.AddField(
            model_name='videocoursereview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.videocoursereview'),
        ),
        migrations.AddField(
            model_name='videocoursereview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='videocoursereview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_video', to='course.videocourse'),
        ),
    ]
