# Generated by Django 5.1.6 on 2025-03-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to='users.student'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_item', to='course.favorite'),
        ),
        migrations.AddField(
            model_name='joinus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_us', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_lessons', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_favorite', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_course', to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.maincourse'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='course.lesson'),
        ),
    ]
