# Generated by Django 5.1.6 on 2025-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinus',
            options={},
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='user',
        ),
        migrations.AddField(
            model_name='joinus',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
