# Generated by Django 5.1.6 on 2025-03-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('users', '0003_owner_owner_course_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to='users.student'),
        ),
    ]
